spring.application.name=AirBnB

spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=Sacchu1998@@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secretKey=a8sd6faihdfjkas2398789afhdskjasdfh87yhk3jha987sdfbjhgebgidebniej
server.servlet.context-path=/api/v1

frontend.url=http://localhost:8080

